Repository wanted-pre-onboarding-backend-django/food-finder, pull requests merged in 2024-09, with the labels that each got.

#26 Chore: 도커라이징 및 PostgreSQL, Redis DB 설정
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  docker-compose.yml
  nginx.conf
  src/config/authentication.py
  src/config/settings.py
  src/restaurant/admin/raw_data_restaurant.py
  src/restaurant/models/raw_data_restaurant.py
  src/restaurant/views/restaurant_detail_view.py
  src/restaurant/views/restaurant_list_view.py
  src/review/utils/update_restaurant_rating.py
  src/review/views/review_view.py
  src/script/data_collection.py
  src/user/models/user.py
  src/user/serializers/user_signup_serializer.py
  src/user/views/user_login_view.py
  src/user/views/user_me_view.py
  src/user/views/user_signup_view.py
Labels: chore

#24 Feat: 대규모 트래픽 대비 캐싱
  Pipfile
  Pipfile.lock
  src/config/settings.py
  src/province/views/province_list_view.py
  src/restaurant/views/restaurant_detail_view.py
  src/review/migrations/0002_alter_review_options_alter_review_table.py
Labels: feat

#27 Feat: Discord Webhook 을 활용한 점심 추천 서비스
  Pipfile
  Pipfile.lock
  README.md
  src/config/apps.py
  src/config/settings.py
  src/restaurant/utils/discord_webhook.py
  src/restaurant/utils/geo_distance.py
  src/restaurant/utils/lunch_recommender.py
  src/restaurant/views/restaurant_list_view.py
  src/script/lunch_rec_scheduler.py
Labels: feat

#28 Doc: README.md 문서 작업
  README.md
Labels: docs

#30 Chore: celery 작업을 위한 설정 추가
  Pipfile
  Pipfile.lock
  docker-compose.yml
  src/config/__init__.py
  src/config/celery.py
  src/config/settings.py
  src/config/tasks.py
Labels: chore
