Repository wanted-pre-onboarding-backend-django/food-finder, pull requests merged in 2024-08, with the labels that each got.

#2 Chore: 빌드 프로세스나 패키지 매니저 설정
  .flake8
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  src/config/__init__.py
  src/config/asgi.py
  src/config/models.py
  src/config/settings.py
  src/config/urls.py
  src/config/wsgi.py
  src/manage.py
Labels: chore

#4 feat:회원가입,로그인
  src/config/authentication.py
  src/config/settings.py
  src/config/urls.py
  src/user/__init__.py
  src/user/admin/__init__.py
  src/user/admin/user_admin.py
  src/user/apps.py
  src/user/migrations/0001_initial.py
  src/user/migrations/__init__.py
  src/user/models/__init__.py
  src/user/models/user.py
  src/user/serializers/__init__.py
  src/user/serializers/user_serializer.py
  src/user/serializers/user_signup_serializer.py
  src/user/tests.py
  src/user/urls.py
  src/user/views/__init__.py
  src/user/views/user_login_view.py
  src/user/views/user_logout_view.py
  src/user/views/user_me_view.py
  src/user/views/user_signup_view.py
Labels: feat

#11 Feat: Restaurant App & Sigungu App 생성
  src/config/settings.py
  src/restaurant/__init__.py
  src/restaurant/admin/__init__.py
  src/restaurant/admin/restaurant_admin.py
  src/restaurant/apps.py
  src/restaurant/migrations/__init__.py
  src/restaurant/models/__init__.py
  src/restaurant/models/restaurant.py
  src/restaurant/serializers/__init__.py
  src/restaurant/urls.py
  src/restaurant/views/__init__.py
  src/sigungu/__init__.py
  src/sigungu/admin/__init__.py
  src/sigungu/admin/sigungu_admin.py
  src/sigungu/apps.py
  src/sigungu/migrations/__init__.py
  src/sigungu/models/__init__.py
  src/sigungu/models/sigungu.py
  src/sigungu/serializers/__init__.py
  src/sigungu/urls.py
  src/sigungu/views/__init__.py
Labels: feat

#14 Data pipeline: Data load 및 collections 스크립트 구현
  Pipfile
  Pipfile.lock
  src/province/admin/__init__.py
  src/province/migrations/0001_initial.py
  src/restaurant/admin/__init__.py
  src/restaurant/admin/raw_data_restaurant.py
  src/restaurant/admin/restaurant_admin.py
  src/restaurant/migrations/0001_initial.py
  src/restaurant/models/__init__.py
  src/restaurant/models/raw_data_restaurant.py
  src/script/data_collection.py
Labels: data_pipeline

#16 Fix: 레스토랑 모델 수정
  src/restaurant/models/restaurant.py
Labels: fix

#18 Feat: 맛집조회
  Pipfile.lock
  src/config/authentication.py
  src/config/settings.py
  src/config/urls.py
  src/province/serializers/__init__.py
  src/province/serializers/province_serializers.py
  src/province/urls.py
  src/province/views/__init__.py
  src/province/views/province_list_view.py
  src/restaurant/admin/restaurant_admin.py
  src/restaurant/migrations/0002_alter_restaurant_category.py
  src/restaurant/migrations/0003_alter_restaurant_unique_together_and_more.py
  src/restaurant/serializers/__init__.py
  src/restaurant/serializers/restaurant_detail_serializer.py
  src/restaurant/serializers/restaurant_list_serializer.py
  src/restaurant/urls.py
  src/restaurant/views/__init__.py
  src/restaurant/views/restaurant_detail_view.py
  src/restaurant/views/restaurant_list_view.py
Labels: feat

#19 Data_Pipeline: 데이터 전처리 작업
  .flake8
  src/script/data_preprocessing.py
Labels: feat, data_pipeline

#20 Feat: 맛집 평가 API
  Pipfile.lock
  src/config/urls.py
  src/province/migrations/0002_alter_province_options_alter_province_table.py
  src/province/models/province.py
  src/review/__init__.py
  src/review/admin/__init__.py
  src/review/admin/review_admin.py
  src/review/apps.py
  src/review/migrations/0001_initial.py
  src/review/migrations/__init__.py
  src/review/models/__init__.py
  src/review/models/review.py
  src/review/serializers/__init__.py
  src/review/serializers/review_serializer.py
  src/review/tests/__init__.py
  src/review/urls.py
  src/review/utils/update_restaurant_rating.py
  src/review/views/__init__.py
  src/review/views/review_view.py
Labels: feat
